In [3]:
import pandas as pd
df = pd.read_csv("globalAirQuality.csv")
# df       
# df.info
# df.sample()
# df.tail()
# df.head()
# df.describe()

# 
# df[["city", "temperature"]]  #this name of columns are case sensitive value and this was to acceess the column value

df.loc[1] #this is for row 
df.loc[0:8] # it will give the data from 0 to  7 index

df.loc[0,"city"]

df.loc[0:3,["city","aqi"]]
df.iloc[0:3,1:5]

df.at[0,"city"]
df.iat[0,2]

'New York'

In [4]:

df[df["aqi"] > 100]
df [(df["aqi"]> 100) & (df["temperature"] >37)]

aqui = df [(df["aqi"]> 100) & (df["temperature"] >37)] [["city","country"]]
aqui
aqui.iloc[0]

city       New York
country          US
Name: 7, dtype: str

In [5]:
import pandas as pd
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [18]:
# learning about quaring 
# query returns the copy of data not view
df.query("aqi >100")
df.query("aqi > 100 & o3 < 7") [["aqi", "o3"]]

aqi_val = 100

df.query("aqi > @aqi_val & o3 < 7") [["aqi", "o3"]]

aqi_data = df.query("aqi > @aqi_val & o3 < 7") [["aqi", "o3"]].copy()
aqi_data

       aqi     o3
128    109  0.114
1501   138  1.488
1809   136  0.627
2006   112  1.839
2297   115  0.736
2910   115  6.077
3568   103  4.879
3839   134  4.328
4807   113  5.018
5138   117  0.326
5437   121  6.669
5450   121  2.582
6139   159  4.938
6709   123  1.053
7024   195  5.395
7133   136  2.692
7523   114  4.857
7658   130  6.986
9427   107  2.995
10281  108  6.841
11261  122  2.125
11825  105  2.158
12767  142  2.222
14362  116  0.600
14883  124  6.175
14995  120  5.316
15875  135  3.234
16051  139  3.989
16389  116  5.082
16770  120  4.306
16924  116  3.116
17229  131  3.499
17774  176  3.285