In [1]:
import pandas as pd

In [16]:
df1 = pd.DataFrame({
    # "name":["kunal",]
    "id":[1,2,3],
    "name":["kunal","Mahesh","Anil"]
})

df2 =pd.DataFrame({
    # "name":["kunal",]
    "id":[4,5,6],
    "name":["Nitin","Abhi","aniket"]
})
pd.concat([df1,df2]) # this is called row or used concatinate on top of each other 
pd.concat([df1,df2], ignore_index =True)

pd.concat([df1,df2], axis = 1)

   id    name  id    name
0   1   kunal   4   Nitin
1   2  Mahesh   5    Abhi
2   3    Anil   6  aniket

In [8]:
df1

   id    name
0   1   kunal
1   2  Mahesh
2   3    Anil

In [9]:
df2

   id    name
0   4   Nitin
1   5    Abhi
2   6  aniket