In [ ]:
import pandas as pd

# Customer Data
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

# Orders Data
df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [10]:
pd.merge(df_customers,df_orders )
pd.merge(df_customers,df_orders, on = "customer_id")   #this is called inner join
pd.merge(df_customers,df_orders, on = "customer_id", how="left") # left join
pd.merge(df_customers,df_orders, on = "customer_id",  how ="right")
pd.merge(df_customers,df_orders, on = "customer_id",  how ="outer")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [9]:
pd.merge(df_customers,df_orders, on = "customer_id")

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300