In [2]:
import pandas as pd

df = pd.read_csv("raw_data.csv")

In [3]:
df.isnull()  #we can also use isna() same meaning 

df.isnull().sum()     #returns the sum of all NaN

df.dropna()

df.dropna(axis = 1)
# df.fillna(0.0)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [4]:
# cleaning the data 
# age_mean = df["age"].mean()

clean_data = df.copy()
age_mean = clean_data["age"].mean()
clean_data["age"] = clean_data["age"].fillna(age_mean)

clean_data

    id          name    age country   gender
0    1      John Doe  29.00     USA     Male
1    1      John Doe  29.00     USA     Male
2    2    Jane Smith  32.75  Canada   Female
3    3          Alex  32.75     USA  Unknown
4    4  Maria Garcia  34.00   Spain   Female
5    5        Li Wei  27.00   China     Male
6    6    Ahmed Khan  45.00   India   Female
7    7           NaN  38.00     NaN     Male
8    8    Rachel Lee  29.00     USA   Female
9    9   Carlos Ruiz  32.75  Mexico      NaN
10  10   Emily Davis  31.00     USA      NaN

In [5]:
df.ffill()  #fills the empty nan with its about row value ex 1,2 (nan)=2
df.bfill()   #visa versa of forward fill and this is bacword fill

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith  34.0  Canada   Female
3    3          Alex  34.0     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6    Ahmed Khan  45.0   India   Female
7    7    Rachel Lee  38.0     USA     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz  31.0  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [6]:
# handale the duplicate value
df.duplicated()
# df["country"].duplicated()
df[["country","gender"]].duplicated()

# df.drop_duplicates(inplace=True)

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [7]:
df

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6    Ahmed Khan  45.0   India   Female
7    7           NaN  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [8]:
# cleaning data (handaling data types)
df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
dtype: object

In [22]:
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] =df2["age"].astype("int64").copy()
df2.dtypes

id          int64
name       object
age         int64
country    object
gender     object
dtype: object

In [23]:
df2

    id          name  age country   gender
0    1      John Doe   29     USA     Male
1    1      John Doe   29     USA     Male
2    2    Jane Smith    0  Canada   Female
3    3          Alex    0     USA  Unknown
4    4  Maria Garcia   34   Spain   Female
5    5        Li Wei   27   China     Male
6    6    Ahmed Khan   45   India   Female
7    7             0   38       0     Male
8    8    Rachel Lee   29     USA   Female
9    9   Carlos Ruiz    0  Mexico        0
10  10   Emily Davis   31     USA        0

In [24]:
aqi_data = pd.read_csv("globalAirQuality.csv")

In [26]:
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [32]:
date_str = pd.Series([pd.to_datetime("2026-3-2")])
type(date_str.dtype)

numpy.dtypes.DateTime64DType